spring.application.name=hwss0801
#config Datasource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/db_jpa_hwss0801
spring.datasource.username=postgres
spring.datasource.password=123456
#config JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#config cloudinary
cloud_name = dnsheem26
api_key = 467697757849325
api_secret = DpjZQhbP1VlRB2LfUcoeTr2M6cs